{
	["OptHRFC"] = "",
	["OptSHNPC"] = "detailed",
	["OptHRST"] = "off",
	["OptDDCL"] = "off",
	["OptTASG"] = "80",
	["OptTOTL"] = "on",
	["OptSHRR"] = "on",
	["sidebar"] = "charsheet,image,table,story,npc,battle,item",
	["OptPSIN"] = "on",
	["OptWINDMEASURE"] = "mph",
	["OptREVL"] = "on",
	["OptRSHE"] = "on",
	["OptIMID"] = "on",
	["OptMIID"] = "on",
	["OptHRNH"] = "random",
	["OptTEMPMEASURE"] = "fahrenheit",
	["OptTNPCH"] = "bar",
	["OptTNAM"] = "tooltip",
	["OptTPCE"] = "on",
	["OptNNPC"] = "append",
	["OptTPCH"] = "bar",
	["OptWNDC"] = "detailed",
	["OptBARC"] = "tiered",
	["OptINIT"] = "off",
	["OptPSMN"] = "on",
	["gmidentity"] = "DM",
}